services:
  books:
    build: ./
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    networks:
      - store-network
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: books
    networks:
      - store-network

networks:
  store-network:
